#!/usr/bin/env python3

# 
#                     _                       
#  _ __ ___  __ _  __| | ___ _ __ _ __  _   _ 
# | '__/ _ \/ _` |/ _` |/ _ \ '__| '_ \| | | |
# | | |  __/ (_| | (_| |  __/ | _| |_) | |_| |
# |_|  \___|\__,_|\__,_|\___|_|(_) .__/ \__, |
#                                |_|    |___/ 
# 
# Read incoming binary block from stdin and write out in hexadecimal text format.
# One sample for each channel, per line.

import sys
import errno
import time
import serial
import serial.tools.list_ports
from pico_control import Pico_control
from settings import Settings


BUFFER_SIZE = 128
BLOCK_SIZE = BUFFER_SIZE * 8
PICO_STARTUP = 'START stream.py 1x 1x 1x 1x 7.812k'


def start_streaming(pico, pico_start_string):
    pico.send_command(pico_start_string)
    response = pico.receive_response()
    print(response, file=sys.stderr)
    # This string returned from Pico means that initialisation was successful
    if 'BINARY' in response:
        return True
    else:
        print(f'{time.ctime()} reader.py, start_streaming(): '
              f'Failed to start streaming on Pico.', file=sys.stderr)
        return False


def read_and_print(pico):
    '''Reads binary data from serial port, and prints as hexadecimal text to stdout.'''
    bs = bytearray(BLOCK_SIZE)
    # We use a 'None' timeout (blocking read) for efficiency, an exception will be thrown if
    # a serial port error occurs.
    pico.ser.timeout = None
    while True:
        try:
            # Read exactly BLOCKSIZE bytes into bytearray buffer.
            pico.ser.readinto(bs)
            # Process data as lines of 8 bytes, or 16 hex characters.
            hexstr = bs.hex()
            for i in range(0, BLOCK_SIZE*2, 16):
                print(f'{hexstr[i:i+4]} {hexstr[i+4:i+8]} {hexstr[i+8:i+12]} {hexstr[i+12:i+16]}')

        except OSError as e:
            if e.errno == errno.EINTR:
                # Continue silently if the read was interrupted by an EINTR signal which can sometimes
                # be generated by other processes that need the bus/CPU.
                pass
            elif e.errno == errno.EPIPE:
                # If there is a broken pipe error, bump the exception out to caller.
                print(f'{time.ctime()} reader.py, read_and_print(): '
                      f'Broken pipe exception, we need to quit.', file=sys.stderr)
                raise e
            else:
                print(f'{time.ctime()} reader.py, read_and_print(): '
                      f'OSError "{e}" during attempt to read from serial port.', file=sys.stderr)
                break

        except IOError as e:
            print(f'{time.ctime()} reader.py, read_and_print(): '
                  f'IOError "{e}" during attempt to read from serial port.', file=sys.stderr)
            break


def main():
    '''Connect to Pico, start streaming program and then read out data.'''
    try:
        # Create a pico object to manage the serial interface and Pico
        pico = Pico_control()
        # Get pico start string from settings
        st = Settings()
        if st.pico_start_string:
            pico_start_string = st.pico_start_string
        else:
            pico_start_string = "START stream.py"
        if pico.find_serial_device() and pico.connect():
            start_streaming(pico, pico_start_string)
            # read_and_print() will continue indefinitely if there are no errors.
            read_and_print(pico)

    except Exception as e:
        # We catch broken pipe and other exceptions here, so that we can clean up.
        print(f'{time.ctime()}: reader.py, main(): '
              f'Exception {e} was caught at exit.', file=sys.stderr)

    finally:
        # Attempt to reset the Pico
        if pico.ser and pico.ser.is_open:
            pico.soft_reset()
        else:
            pico.hard_reset()
        # The reset operation will close the port, but we check just in case.
        if pico.ser and pico.ser.is_open:
            pico.disconnect()
        print(f'{time.ctime()} reader.py, main(): Now exiting.', file=sys.stderr)


if __name__ == '__main__':
    main()


